const foods=[
{id:1,n:"Masala Dosa",c:"breakfast",p:45,e:"🥞",d:"Crispy dosa with potato masala & chutney",a:true},
{id:2,n:"Idli Sambar",c:"breakfast",p:30,e:"🍘",d:"Soft idlis served with hot sambar",a:true},
{id:3,n:"Veg Meals",c:"lunch",p:70,e:"🍛",d:"Rice, sambar, poriyal, rasam & curd",a:true},
{id:4,n:"Lemon Rice",c:"lunch",p:40,e:"🍋",d:"Tangy lemon rice with crunchy peanuts",a:true},
{id:5,n:"Samosa",c:"snacks",p:20,e:"🥟",d:"Crispy vegetable samosa",a:true},
{id:6,n:"Tea",c:"snacks",p:15,e:"☕",d:"Hot milk tea",a:true}];
let cart=JSON.parse(localStorage.getItem("scCart")||"[]"),orders=JSON.parse(localStorage.getItem("scOrders")||"[]");
const $=id=>document.getElementById(id);function persist(){localStorage.setItem("scCart",JSON.stringify(cart));localStorage.setItem("scOrders",JSON.stringify(orders));$("count").textContent=cart.reduce((s,x)=>s+x.q,0)}
function render(filter="all"){$("foodGrid").innerHTML=foods.filter(f=>filter==="all"||f.c===filter).map(f=>`<article class="card"><div class="pic">${f.e}</div><div class="body"><h3>${f.n}</h3><p>${f.d}</p><div class="foot"><span class="price">₹${f.p}</span>${f.a?`<button class="add" onclick="add(${f.id})">+ Add</button>`:`<span class="sold">Sold out</span>`}</div></div></article>`).join("")}
function add(id){let x=cart.find(x=>x.id===id);x?x.q++:cart.push({id,q:1});persist();toast("Added to cart")}
function openCart(){renderCart();$("modal").classList.remove("hidden")}
function closeCart(){$("modal").classList.add("hidden")}
function renderCart(){let total=0;let c=$("cart");if(!cart.length){c.innerHTML='<div class="empty">Your cart is empty.</div>'}else c.innerHTML=cart.map(x=>{let f=foods.find(y=>y.id===x.id);total+=f.p*x.q;return `<div class="cartLine"><span>${f.e} ${f.n} × ${x.q}</span><b>₹${f.p*x.q}</b></div>`}).join("");$("foodTotal").textContent="₹"+total;$("grand").textContent="₹"+(total+(document.querySelector('input[name="method"]:checked')?.value==="room"?5:0))}
document.addEventListener("change",e=>{if(e.target.name==="method"){$("roomFields").style.display=e.target.value==="room"?"block":"none";renderCart()}});
function placeOrder(){if(!cart.length)return toast("Add food first");let method=document.querySelector('input[name="method"]:checked').value;let block=$("block").value.trim(),floor=$("floor").value.trim(),room=$("room").value.trim();if(method==="room"&&(!block||!floor||!room))return toast("Enter block, floor and room number");let total=cart.reduce((s,x)=>s+foods.find(f=>f.id===x.id).p*x.q,0)+(method==="room"?5:0);let token=1048+orders.length;orders.unshift({token,items:cart.map(x=>({...x})),total,method,status:method==="room"?"Order received":"Preparing",address:method==="room"?`${block}, Floor ${floor}, Room ${room}`:"Canteen pickup",time:new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})});cart=[];persist();closeCart();show("orders");toast("Order #"+token+" placed successfully")}
function show(id){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.page===id));if(id==="orders")renderOrders();if(id==="delivery")renderDelivery();scrollTo(0,0)}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>show(b.dataset.page));document.querySelectorAll(".filters button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");render(b.dataset.filter)});
function renderOrders(){if(!orders.length){$("orderList").innerHTML='<div class="empty">No orders yet. Order something from the menu.</div>';return}$("orderList").innerHTML=orders.map(o=>`<div class="order"><div class="orderHead"><div><b>Token #${o.token}</b><p class="meta">${o.time} · ${o.address} · ₹${o.total}</p></div><span class="status">${o.status}</span></div><div class="steps"><span class="done">✓ Placed</span><span class="${["Preparing","Out for delivery","Ready","Delivered"].includes(o.status)?"done":""}">✓ Preparing</span><span class="${["Out for delivery","Ready","Delivered"].includes(o.status)?"done":""}">○ Out for delivery</span><span class="${o.status==="Delivered"?"done":""}">○ Delivered</span></div></div>`).join("")}
function renderDelivery(){let active=orders.filter(o=>o.method==="room"&&o.status!=="Delivered");$("active").textContent=3+active.length;$("today").textContent=47+orders.length;$("deliveryList").innerHTML=active.length?active.map(o=>`<div class="drow"><div><b>#${o.token}</b> · ${o.address}<br><span class="meta">${o.status} · ₹${o.total}</span></div><button class="deliver" onclick="advance(${o.token})">${o.status==="Order received"?"Start preparing":o.status==="Preparing"?"Out for delivery":"Mark delivered"}</button></div>`).join(""):'<div class="empty">No active room deliveries.</div>';$("adminMenu").innerHTML=foods.map(f=>`<div class="mrow"><span>${f.e} ${f.n}</span><button class="toggle ${f.a?"on":"off"}" onclick="toggle(${f.id})">${f.a?"Available":"Sold out"}</button></div>`).join("")}
function advance(token){let o=orders.find(x=>x.token===token);o.status=o.status==="Order received"?"Preparing":o.status==="Preparing"?"Out for delivery":"Delivered";persist();renderDelivery();renderOrders();toast(o.status==="Delivered"?"Delivered to "+o.address:"Order #"+token+" updated")}
function toggle(id){let f=foods.find(x=>x.id===id);f.a=!f.a;render();renderDelivery();toast(f.n+" is now "+(f.a?"available":"sold out"))}
function toast(t){let e=$("toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)}
render();persist();